// const initialFacts = [
//   {
//     id: 1,
//     text: "React is being developed by Meta (formerly facebook)",
//     source: "https://opensource.fb.com/",
//     category: "technology",
//     votesInteresting: 24,
//     votesMindblowing: 9,
//     votesFalse: 4,
//     createdIn: 2021,
//   },
//   {
//     id: 2,
//     text: "Millennial dads spend 3 times as much time with their kids than their fathers spent with them. In 1982, 43% of fathers had never changed a diaper. Today, that number is down to 3%",
//     source:
//       "https://www.mother.ly/parenting/millennial-dads-spend-more-time-with-their-kids",
//     category: "society",
//     votesInteresting: 11,
//     votesMindblowing: 2,
//     votesFalse: 0,
//     createdIn: 2019,
//   },
//   {
//     id: 3,
//     text: "Lisbon is the capital of Portugal",
//     source: "https://en.wikipedia.org/wiki/Lisbon",
//     category: "society",
//     votesInteresting: 8,
//     votesMindblowing: 3,
//     votesFalse: 1,
//     createdIn: 2015,
//   },
// ];

// const initialFacts = [
//   {
//     id: 1,
//     text: "The shortest war in history lasted 38 minutes! It was between Britain and Zanzibar on August 27, 1896. It was over the ascension of the next Sultan in Zanzibar and resulted in a British victory.",
//     source:
//       "https://www.historic-uk.com/HistoryUK/HistoryofBritain/The-Shortest-War-in-History/#:~:text=The%20little%20known%20Anglo%2DZanzibar,Britain%20and%20Germany%20in%201890.",
//     category: "history",
//     votesInteresting: 15,
//     votesMindblowing: 2,
//     votesFalse: 2,
//     createdIn: 2024,
//   },
//   {
//     id: 2,
//     text: "The less money you spend, the more you save!",
//     source:
//       "https://bettermoneyhabits.bankofamerica.com/en/saving-budgeting/ways-to-save-money",
//     category: "finance",
//     votesInteresting: 5,
//     votesMindblowing: 2,
//     votesFalse: 3,
//     createdIn: 2024,
//   },
//   {
//     id: 3,
//     text: "Millennial dads spend 3 times as much time with their kids than their fathers spent with them. In 1982, 43% of fathers had never changed a diaper. Today, that number is down to 3%",
//     source:
//       "https://www.mother.ly/parenting/millennial-dads-spend-more-time-with-their-kids/?rebelltitem=1#rebelltitem1",
//     category: "society",
//     votesInteresting: 2,
//     votesMindblowing: 0,
//     votesFalse: 0,
//     createdIn: 2024,
//   },
//   {
//     id: 4,
//     text: "As of 2023, Breaking Bad is the highest-rated TV show on IMDb with a rating of 9.4/10",
//     source: "https://www.imdb.com/chart/toptv/",
//     category: "entertainment",
//     votesInteresting: 10,
//     votesMindblowing: 9,
//     votesFalse: 8,
//     createdIn: 2024,
//   },
//   {
//     id: 5,
//     text: "The first 1GB hard drive was made in 1980 and had a price of $40,000!",
//     source:
//       "https://www.autodesk.com/products/fusion-360/blog/a-look-back-at-the-first-built-in-hard-drive/#:~:text=The%20Rapidly%20Evolving%20HDD&text=In%201980%2C%20we%20saw%20the,around%20for%20a%20long%20time.",
//     category: "history",
//     votesInteresting: 38,
//     votesMindblowing: 32,
//     votesFalse: 47,
//     createdIn: 2024,
//   },
//   {
//     id: 6,
//     text: "Lisbon is the capital of Portugal",
//     source: "https://en.wikipedia.org/wiki/Lisbon",
//     category: "society",
//     votesInteresting: 12,
//     votesMindblowing: 4,
//     votesFalse: 3,
//     createdIn: 2024,
//   },
//   {
//     id: 7,
//     text: "React was developed by Google",
//     source: "https://example.com",
//     category: "it",
//     votesInteresting: 26,
//     votesMindblowing: 0,
//     votesFalse: 0,
//     createdIn: 2024,
//   },
//   {
//     id: 8,
//     text: "yo yo yo",
//     source: "http://example.com",
//     category: "news",
//     votesInteresting: 14,
//     votesMindblowing: 6,
//     votesFalse: 22,
//     createdIn: 2024,
//   },
//   {
//     id: 9,
//     text: "React is being developed by Meta (formerly facebook)",
//     source: "https://opensource.fb.com/",
//     category: "it",
//     votesInteresting: 14,
//     votesMindblowing: 0,
//     votesFalse: 0,
//     createdIn: 2024,
//   },
//   {
//     id: 10,
//     text: "Human DNA is 99.9% identical from person to person",
//     source:
//       "https://www.genome.gov/about-genomics/fact-sheets/Genetics-vs-Genomics",
//     category: "science",
//     votesInteresting: 76,
//     votesMindblowing: 5,
//     votesFalse: 13,
//     createdIn: 2024,
//   },
//   {
//     id: 11,
//     text: '"typewriter" is the longest English word you can type using 1 row of the QWERTY keyboard',
//     source: "https://twitter.com/intel/status/442074967522684928",
//     category: "it",
//     votesInteresting: 6,
//     votesMindblowing: 4,
//     votesFalse: 1,
//     createdIn: 2024,
//   },
//   {
//     id: 12,
//     text: "There is enough DNA in the average person’s body to stretch from the sun to Pluto and back — 17 times",
//     source:
//       "https://skeptics.stackexchange.com/questions/10606/length-of-uncoiled-human-dna",
//     category: "science",
//     votesInteresting: 9,
//     votesMindblowing: 2,
//     votesFalse: 1,
//     createdIn: 2024,
//   },
// ];

const initialFacts = [
  {
    id: 1,
    text: "The Voyager 1 spacecraft is the most distant human-made object from Earth, having traveled more than 14 billion miles since its launch in 1977.",
    source: "https://voyager.jpl.nasa.gov/mission/status/",
    category: "aerospace",
    votesInteresting: 25,
    votesMindblowing: 18,
    votesFalse: 1,
    createdIn: 2024,
  },
  {
    id: 2,
    text: "The world’s largest producer of coffee is Brazil, which accounts for about one-third of the global production.",
    source: "https://www.worldatlas.com/articles/top-coffee-producers.html",
    category: "agriculture",
    votesInteresting: 15,
    votesMindblowing: 5,
    votesFalse: 0,
    createdIn: 2024,
  },
  {
    id: 3,
    text: "The Burj Khalifa in Dubai is the tallest building in the world, standing at 828 meters (2,717 feet) tall.",
    source: "https://www.burjkhalifa.ae/en/the-tower/facts-figures/",
    category: "architecture",
    votesInteresting: 35,
    votesMindblowing: 28,
    votesFalse: 2,
    createdIn: 2024,
  },
  {
    id: 4,
    text: "The periodic table of elements was first created by Dmitri Mendeleev in 1869.",
    source: "https://www.rsc.org/periodic-table/history/about",
    category: "chemistry",
    votesInteresting: 20,
    votesMindblowing: 7,
    votesFalse: 3,
    createdIn: 2024,
  },
  {
    id: 5,
    text: "The first practical electrical circuit was created by Alessandro Volta in 1800 with his invention of the voltaic pile.",
    source: "https://www.britannica.com/biography/Alessandro-Volta",
    category: "electronic",
    votesInteresting: 18,
    votesMindblowing: 9,
    votesFalse: 4,
    createdIn: 2024,
  },
  {
    id: 6,
    text: "JavaScript was created in just 10 days by Brendan Eich in 1995.",
    source:
      "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction",
    category: "it",
    votesInteresting: 30,
    votesMindblowing: 12,
    votesFalse: 5,
    createdIn: 2024,
  },
  {
    id: 7,
    text: "The Eiffel Tower was initially intended to be a temporary installation, standing for only 20 years after the 1889 World’s Fair.",
    source: "https://www.toureiffel.paris/en/the-monument/history",
    category: "architecture",
    votesInteresting: 22,
    votesMindblowing: 16,
    votesFalse: 3,
    createdIn: 2024,
  },
  {
    id: 8,
    text: "Graphene is one of the strongest materials known, with a tensile strength of 130 GPa, which is more than 100 times stronger than steel.",
    source:
      "https://www.graphene.manchester.ac.uk/learn/discovery-and-development/",
    category: "materials",
    votesInteresting: 40,
    votesMindblowing: 25,
    votesFalse: 2,
    createdIn: 2024,
  },
  {
    id: 9,
    text: "The first steam engine was developed by Thomas Newcomen in 1712 to pump water out of mines.",
    source: "https://www.britannica.com/biography/Thomas-Newcomen",
    category: "mechanics",
    votesInteresting: 12,
    votesMindblowing: 6,
    votesFalse: 1,
    createdIn: 2024,
  },
  {
    id: 10,
    text: "The Boeing 747, known as the 'Queen of the Skies,' was the first wide-body airplane ever produced and held the passenger capacity record for 37 years.",
    source: "https://www.boeing.com/history/products/747.page",
    category: "aerospace",
    votesInteresting: 55,
    votesMindblowing: 45,
    votesFalse: 8,
    createdIn: 2024,
  },
];

const CATEGORIES = [
  { name: "aerospace", color: "#3b82f6" },
  { name: "agriculture", color: "#16a34a" },
  { name: "architecture", color: "#ef4444" },
  { name: "chemistry", color: "#db2777" },
  { name: "electronic", color: "#eab308" },
  { name: "it", color: "#f97316" },
  { name: "materials", color: "#14b8a6" },
  { name: "mechanics", color: "#8b5cf6" },
];

export default initialFacts;
